
os: osx
osx_image: xcode7.3

cache:
  directories:
    - /Library/Developer/Toolchains

before_install:
  - openssl aes-256-cbc -K $encrypted_a6399d1c22a9_key -iv $encrypted_a6399d1c22a9_iv -in Tests/InsightsForWeather/Credentials.swift.enc -out Tests/InsightsForWeather/Credentials.swift -d
  - brew install gnu-sed http-parser curl hiredis
  - wget https://swift.org/builds/development/xcode/swift-DEVELOPMENT-SNAPSHOT-2016-04-25-a/swift-DEVELOPMENT-SNAPSHOT-2016-04-25-a-osx.pkg
  - sudo installer -pkg swift-DEVELOPMENT-SNAPSHOT-2016-04-25-a-osx.pkg -target /
  - export PATH=/Library/Developer/Toolchains/swift-latest.xctoolchain/usr/bin:"${PATH}"

script:
    - swift build
    - swift test
